#!/bin/bash

set -o pipefail

DIR="$(
  cd "$(dirname "$0")" || exit 1
  pwd
)"
# shellcheck source=/dev/null
. "$DIR/../utils"

# Check git, if not exists, exec apply_git
if ! command_exists git; then
  /bin/bash "$DIR/apply_git"
fi

: "${MIRROR:=false}"

if ! command_exists zsh; then
  install_app zsh
fi

chsh -s "$(which zsh)" "$(whoami)"

# Link zsh files
ln -snf "$DIR/zsh/.zprofile" "$HOME/.zprofile"
ln -snf "$DIR/zsh/.zshrc" "$HOME/.zshrc"
ln -snf "$DIR/zsh/.zshenv" "$HOME/.zshenv"
ln -snf "$DIR/zsh/.p10k.zsh" "$HOME/.p10k.zsh"

# Install oh-my-zsh if not exists
if [ ! -d "$HOME/.oh-my-zsh" ]; then
  if ! command_exists curl; then
    install_app curl
  fi

  if $MIRROR; then
    curl -fsSL https://git.duskmoon314.com/mirrors/ohmyzsh/raw/branch/master/tools/install.sh |
      REMOTE=https://git.duskmoon314.com/mirrors/ohmyzsh.git KEEP_ZSHRC=yes sh
  else
    curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh |
      KEEP_ZSHRC=yes sh
  fi
fi

# Clone powerlevel10k if not exists
if [ ! -d "$HOME/.oh-my-zsh/custom/themes/powerlevel10k" ]; then
  if $MIRROR; then
    git clone --depth=1 https://gitee.com/romkatv/powerlevel10k.git "$HOME/.oh-my-zsh/custom/themes/powerlevel10k"
  else
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "$HOME/.oh-my-zsh/custom/themes/powerlevel10k"
  fi
fi

# Clone zsh-autosuggestions if not exists
if [ ! -d "$HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions" ]; then
  if $MIRROR; then
    git clone --depth=1 https://git.duskmoon314.com/mirrors/zsh-autosuggestions.git "$HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  else
    git clone --depth=1 https://github.com/zsh-users/zsh-autosuggestions.git "$HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  fi
fi

# Clone zsh-syntax-highlighting if not exists
if [ ! -d "$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting" ]; then
  if $MIRROR; then
    git clone --depth=1 https://git.duskmoon314.com/mirrors/zsh-syntax-highlighting.git "$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
  else
    git clone --depth=1 https://github.com/zsh-users/zsh-syntax-highlighting.git "$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
  fi
fi
