#!/bin/bash

apply_exa() {
  echo "===== Apply exa ====="

  if ! command_exists exa; then
    INFO "Installing exa..."

    if [ $ROOT_USER = 0 ]; then
      install_app exa
    else
      # TODO: Install exa without root
      WARN "Unsupported yet: Install exa without root"
      return 1
    fi
  fi

  INFO "Installing exa: Done"

  if $REPLACE_LINUX_COMMON; then
    set_alias_to_shrc ls exa
    set_alias_to_shrc ll 'exa -l'
    set_alias_to_shrc la 'exa -la'
  fi

  INFO "Apply exa: Done"
}

apply_exa
