#!/bin/bash

set -euo pipefail

DIR="$(
  cd "$(dirname "$0")" || exit 1
  pwd
)"
# shellcheck source=/dev/null
. "$DIR/../utils"

: "${REPLACE_WITH_MODERN_UNIX:=false}"

if ! command_exists bat; then
  REPLACE_WITH_MODERN_UNIX=$REPLACE_WITH_MODERN_UNIX \
    /bin/bash "$DIR/apply_bat"
fi

if ! command_exists exa; then
  REPLACE_WITH_MODERN_UNIX=$REPLACE_WITH_MODERN_UNIX \
    /bin/bash "$DIR/apply_exa"
fi

if ! command_exists fd; then
  REPLACE_WITH_MODERN_UNIX=$REPLACE_WITH_MODERN_UNIX \
    /bin/bash "$DIR/apply_fd"
fi

if ! command_exists rg; then
  REPLACE_WITH_MODERN_UNIX=$REPLACE_WITH_MODERN_UNIX \
    /bin/bash "$DIR/apply_ripgrep"
fi
