#!/bin/bash

set -euo pipefail

DIR="$(
  cd "$(dirname "$0")" || exit 1
  pwd
)"
# shellcheck source=/dev/null
. "$DIR/../utils"

: "${REPLACE_WITH_MODERN_UNIX:=false}"

if ! command_exists bat; then
  install_app bat
fi
if $REPLACE_WITH_MODERN_UNIX; then
  if [ -f "/etc/os-release" ] && grep -q 'Debian\|Ubuntu' /etc/os-release; then
    set_alias_to_shrc bat batcat
    set_alias_to_shrc cat batcat
  else
    set_alias_to_shrc cat bat
  fi
fi

# Note: May adding opinioned config here in the future
