#!/bin/bash

set -euo pipefail

DIR="$(
  cd "$(dirname "$0")" || exit 1
  pwd
)"
# shellcheck source=/dev/null
. "$DIR/../utils"

: "${INSTALL_NVIM:=true}"
: "${INSTALL_NVIM_LATEST:=true}"

if ! $INSTALL_NVIM; then
  if ! command_exists vim; then
    install_app vim
  fi
else
  # Install neovim

  if $INSTALL_NVIM_LATEST; then
    echo "Installing neovim appimage, please check FUSE support"

    # Download nvim.appimage
    if command_exists wget; then
      wget -O /tmp/nvim.appimage https://github.com/neovim/neovim/releases/download/stable/nvim.appimage
    elif command_exists curl; then
      curl -fsSL https://github.com/neovim/neovim/releases/download/stable/nvim.appimage -o /tmp/nvim.appimage
    else
      echo "Failed to find wget or curl to download nvim.appimage"
      exit 1
    fi

    as_root chmod +x /tmp/nvim.appimage
    as_root mv /tmp/nvim.appimage /usr/local/bin/nvim
  else
    if ! command_exists nvim; then
      install_app neovim
    fi
  fi
fi

# Link vimrc
ln -snf "$DIR/vim/.vimrc" "$HOME/.vimrc"
