#!/bin/bash

apply_ripgrep() {
  if ! command_exists rg; then
    INFO "Installing ripgrep..."

    if [ $ROOT_USER = 0 ]; then
      install_app ripgrep
    else
      # TODO: Install ripgrep without root
      WARN "Unsupported yet: Install ripgrep without root"
      return 1
    fi
  fi

  INFO "Installing ripgrep: Done"

  if $REPLACE_LINUX_COMMON; then
    set_alias_to_shrc grep rg
  fi
}

apply_ripgrep
