#!/bin/bash

apply_sshd() {
  echo "===== Apply sshd ====="
  echo "Pleas make sure public keys are added"

  if ! command_exists sshd; then
    INFO "Installing sshd..."

    if [ "$ROOT_USER" = 0 ]; then
      case $OS in
      Debian | Ubuntu)
        install_app openssh-server
        ;;
      *)
        WARN "Unsupported OS"
        return 1
        ;;
      esac
    else
      # TODO: Install sshd for non-root user
      WARN "Unsupported yet: Install sshd for non-root user"
      return 1
    fi
  fi

  INFO "Configuring sshd..."
  INFO "Password Authentication will be disabled"

  if [ "$ROOT_USER" = 0 ]; then
    as_root tee -a /etc/ssh/sshd_config <<EOF
PasswordAuthentication no
AuthenticationMethods publickey
PermitRootLogin prohibit-password
EOF
    as_root mkdir -p /run/sshd
  else
    # TODO
    WARN "Unsupported yet: Configure sshd for non-root user"
  fi

  if $RESTART_SERVICE; then
    INFO "Restarting sshd..."
    if command_exists systemctl; then
      as_root systemctl restart sshd.service
    elif command_exists service; then
      as_root service ssh restart
    else
      ERROR "Unknown service manager"
      exit 1
    fi
  fi
}

apply_sshd
