#!/bin/bash

set -o pipefail

DIR="$(
  cd "$(dirname "$0")" || exit 1
  pwd
)"
# shellcheck source=/dev/null
. "$DIR/../utils"

if ! command_exists git; then
  install_app git
fi

# Allow cloning over HTTPS
install_app ca-certificates

ln -snf "$DIR/git/.gitconfig" "$HOME/.gitconfig"
