#!/bin/bash

apply_git() {
  echo "===== Apply git ===="

  if ! command_exists git; then
    echo "Installing git"

    if [ $ROOT_USER = 0 ]; then
      install_app ca-certificates git
    else
      # TODO: Install git without root
      WARN "What a nightmare! Install git without root is not supported yet."
    fi
  fi

  ln -snf "$DIR/git/.gitconfig" "$HOME/.gitconfig"
}

apply_git
