#!/bin/bash

set -euo pipefail

DIR="$(
  cd "$(dirname "$0")" || exit 1
  pwd
)"
# shellcheck source=/dev/null
. "$DIR/../utils"

: "${REPLACE_WITH_MODERN_UNIX:=false}"

if ! command_exists rg; then
  install_app ripgrep
fi
if $REPLACE_WITH_MODERN_UNIX; then
  set_alias_to_shrc grep rg
fi

# Note: May adding opinioned config here in the future
