#!/bin/bash

set -euo pipefail

DIR="$(
  cd "$(dirname "$0")" || exit 1
  pwd
)"
# shellcheck source=/dev/null
. "$DIR/../utils"

if ! command_exists curl; then
  echo "curl is required to install Go"
  exit 1
fi

# go<major>.<minor>.<patch>
GO_LATEST_VERSION=$(curl https://go.dev/dl/?mode=json | grep -o 'go[0-9]\.[0-9]\+\(\.[0-9]\+\)\?' | head -n 1 | tr -d '\r\n')
: "${GO_VERSION:=$GO_LATEST_VERSION}"

# Get OS and ARCH
OS=$(uname -s | tr '[:upper:]' '[:lower:]')
ARCH=$(uname -m)
case $ARCH in
x86_64)
  ARCH=amd64
  ;;
aarch64 | arm64)
  ARCH=arm64
  ;;
i386 | i686)
  ARCH="386"
  ;;
*)
  echo "Unsupported architecture: $ARCH"
  exit 1
  ;;
esac

# Download and install Go
curl -sSL "https://go.dev/dl/${GO_VERSION}.${OS}-${ARCH}.tar.gz" -o go.tar.gz
as_root tar -C /usr/local -xzf go.tar.gz
