#!/bin/bash

apply_apt() {
  echo "===== Apply apt ====="

  if [ "$ROOT_USER" = 0 ]; then
    case $OS in
    ubuntu)
      . /etc/os-release

      if dpkg-query -W -f='${Status}' ca-certificates 2>/dev/null | grep -q "ok installed"; then
        INFO "ca-certificates is already installed"
      else
        install_app ca-certificates
      fi

      if ! $MIRROR; then
        INFO "Skip setting apt mirror"
        return 0
      fi

      INFO "Backup old apt sources"
      if [ -f /etc/apt/sources.list ]; then
        as_root cp /etc/apt/sources.list /etc/apt/sources.list.bak-"$(date +%Y%m%d%H%M%S)"
      fi
      isa=$(uname -i)
      if [ "$isa" = 'x86_64' ]; then
        as_root tee /etc/apt/sources.list <<EOF
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ $VERSION_CODENAME main restricted universe multiverse
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ $VERSION_CODENAME-updates main restricted universe multiverse
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ $VERSION_CODENAME-backports main restricted universe multiverse
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ $VERSION_CODENAME-security main restricted universe multiverse
# deb http://security.ubuntu.com/ubuntu $VERSION_CODENAME-security main restricted universe multiverse
EOF
      else
        as_root tee /etc/apt/sources.list <<EOF
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ $VERSION_CODENAME main restricted universe multiverse
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ $VERSION_CODENAME-updates main restricted universe multiverse
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ $VERSION_CODENAME-backports main restricted universe multiverse
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ $VERSION_CODENAME-security main restricted universe multiverse
# deb http://ports.ubuntu.com/ubuntu-ports $VERSION_CODENAME-security main restricted universe multiverse
EOF
      fi
      ;;
    *)
      WARN "Unsupported OS: $OS"
      return 1
      ;;
    esac
  else
    WARN "This script must be run as root"
    return 1
  fi

}

apply_apt
