#!/bin/bash

apply_fd() {
  echo "===== Apply fd ====="

  if ! command_exists fd && ! command_exists fdfind; then
    INFO "Installing fd..."

    if [ $ROOT_USER = 0 ]; then
      case $OS in
      Ubuntu | Debian)
        install_app fd-find
        ;;
      *)
        install_app fd
        ;;
      esac
    else
      # Non-root user and can't use sudo/su
      # TODO: Install fd without root
      WARN "Unsupported yet: Install fd without root"
      return 1
    fi
  fi

  INFO "Installing fd: Done"

  if $REPLACE_LINUX_COMMON; then
    case $OS in
    Ubuntu | Debian)
      set_alias_to_shrc fd fdfind
      set_alias_to_shrc find fdfind
      ;;
    *)
      set_alias_to_shrc find fd
      ;;
    esac
  fi

  INFO "Apply fd: Done"
}

apply_fd
